version: "3.3"
services:

  # Container for running the latest deployment
  facetorch:
    image: tomasgajarsky/facetorch:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
        - ./:/opt/facetorch
    entrypoint: ["/bin/bash"]

  facetorch-gpu:
    image: tomasgajarsky/facetorch-gpu:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
        - ./:/opt/facetorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    entrypoint: ["/bin/bash"]

  facetorch-gpu-no-device:
    image: tomasgajarsky/facetorch-gpu:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
        - ./:/opt/facetorch
    entrypoint: ["/bin/bash"]