version: "3.3"
services:
  # Container for development purposes
  liveness-detection:
    platform: linux/amd64
    # name: liveness-detector
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    restart: always
    tty: true
    ports:
      - "11322:11322"
    volumes:
      - ./:/opt/facetorch
    # command: python3 ./scripts/app.py
    entrypoint: ["/bin/bash"]
    depends_on:
      - fas
      - vectordb
    networks:
      - liveness-net

  vectordb:
    # name: vectordb
    image: qdrant/qdrant
    restart: always
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    networks:
      - liveness-net

  fas:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fas
    command: python3 fas_app.py 
    # entrypoint: ["/bin/bash"]
    tty: true
    volumes:
      - ./models:/opt/fas/models
      - ./scripts/fas_app.py:/opt/fas/fas_app.py
    networks:
      - liveness-net

networks:
  liveness-net:
    driver: bridge 
